package exampleutil

// Generated by slicemeta-0.0.1a (2018-01-05T20:40:44-08:00)

import "github.com/azavorotnii/slicemeta/internal/example"

func Equal(a, b []example.Example) bool {
	if len(a) != len(b) {
		return false
	}
	for i := 0; i < len(a); i++ {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
