package exampleutil

// Generated by slicemeta-0.0.1a (2018-01-05T20:40:44-08:00)

import "github.com/azavorotnii/slicemeta/internal/example"

func Index(in []example.Example, value example.Example) int {
	for i, v := range in {
		if v == value {
			return i
		}
	}
	return -1
}

func IndexAny(in []example.Example, values []example.Example) int {
	for i, v := range in {
		for _, value := range values {
			if v == value {
				return i
			}
		}
	}
	return -1
}

func IndexFunc(in []example.Example, f func(example.Example) bool) int {
	for i, v := range in {
		if f(v) {
			return i
		}
	}
	return -1
}
