package stringutil

// Generated by slicemeta-0.0.1a (2018-01-05T20:27:51-08:00)

func Contains(in []string, value string) bool {
	for _, v := range in {
		if v == value {
			return true
		}
	}
	return false
}
